export const current_ride_sharing_data = [
    {
        "vehicle_owner_number": 100001,
        "departure": "Limerick",
        "destination": "Dublin",
        "departure_time": "2023-12-02",
        "distance": 100,
        "class": "A",
        "energy_efficiency_rating": "high",
        "publish_timestamp": 1700504313,
        "vacancy": 4,
        "total_carbon_emission_reduction": 0
    },
    {
        "vehicle_owner_number": 100002,
        "departure": "Galway",
        "destination": "Limerick",
        "departure_time": "2023-12-08",
        "distance": 100,
        "class": "A",
        "energy_efficiency_rating": "mid",
        "publish_timestamp": 1700504313,
        "vacancy": 5,
        "total_carbon_emission_reduction": 0
    },
    {
        "vehicle_owner_number": 100003,
        "departure": "Dublin",
        "destination": "Cork",
        "departure_time": "2023-11-27",
        "distance": 50,
        "class": "A",
        "energy_efficiency_rating": "high",
        "publish_timestamp": 1700504313,
        "vacancy": 3,
        "total_carbon_emission_reduction": 0
    },
    {
        "vehicle_owner_number": 100004,
        "departure": "Cork",
        "destination": "Galway",
        "departure_time": "2023-12-15",
        "distance": 100,
        "class": "A",
        "energy_efficiency_rating": "high",
        "publish_timestamp": 1700504313,
        "vacancy": 3,
        "total_carbon_emission_reduction": 0
    },
    {
        "vehicle_owner_number": 100005,
        "departure": "Galway",
        "destination": "Dublin",
        "departure_time": "2023-11-23",
        "distance": 50,
        "class": "A",
        "energy_efficiency_rating": "high",
        "publish_timestamp": 1700504313,
        "vacancy": 4,
        "total_carbon_emission_reduction": 0
    },
    {
        "vehicle_owner_number": 100006,
        "departure": "Galway",
        "destination": "Waterford",
        "departure_time": "2023-11-24",
        "distance": 100,
        "class": "C",
        "energy_efficiency_rating": "mid",
        "publish_timestamp": 1700504313,
        "vacancy": 1,
        "total_carbon_emission_reduction": 0
    },
    {
        "vehicle_owner_number": 100007,
        "departure": "Galway",
        "destination": "Cork",
        "departure_time": "2023-12-11",
        "distance": 100,
        "class": "A",
        "energy_efficiency_rating": "mid",
        "publish_timestamp": 1700504313,
        "vacancy": 4,
        "total_carbon_emission_reduction": 0
    },
    {
        "vehicle_owner_number": 100008,
        "departure": "Cork",
        "destination": "Dublin",
        "departure_time": "2023-12-13",
        "distance": 50,
        "class": "A",
        "energy_efficiency_rating": "mid",
        "publish_timestamp": 1700504313,
        "vacancy": 6,
        "total_carbon_emission_reduction": 0
    },
    {
        "vehicle_owner_number": 100009,
        "departure": "Dublin",
        "destination": "Galway",
        "departure_time": "2023-12-03",
        "distance": 50,
        "class": "C",
        "energy_efficiency_rating": "high",
        "publish_timestamp": 1700504313,
        "vacancy": 5,
        "total_carbon_emission_reduction": 0
    },
    {
        "vehicle_owner_number": 1000010,
        "departure": "Waterford",
        "destination": "Dublin",
        "departure_time": "2023-11-23",
        "distance": 50,
        "class": "A",
        "energy_efficiency_rating": "high",
        "publish_timestamp": 1700504313,
        "vacancy": 4,
        "total_carbon_emission_reduction": 0
    },
    {
        "vehicle_owner_number": 1000011,
        "departure": "Limerick",
        "destination": "Waterford",
        "departure_time": "2023-12-12",
        "distance": 100,
        "class": "A",
        "energy_efficiency_rating": "low",
        "publish_timestamp": 1700504313,
        "vacancy": 6,
        "total_carbon_emission_reduction": 0
    },
    {
        "vehicle_owner_number": 1000012,
        "departure": "Galway",
        "destination": "Limerick",
        "departure_time": "2023-11-22",
        "distance": 50,
        "class": "B",
        "energy_efficiency_rating": "mid",
        "publish_timestamp": 1700504313,
        "vacancy": 3,
        "total_carbon_emission_reduction": 0
    },
    {
        "vehicle_owner_number": 1000013,
        "departure": "Galway",
        "destination": "Limerick",
        "departure_time": "2023-12-15",
        "distance": 50,
        "class": "A",
        "energy_efficiency_rating": "mid",
        "publish_timestamp": 1700504313,
        "vacancy": 5,
        "total_carbon_emission_reduction": 0
    },
    {
        "vehicle_owner_number": 1000014,
        "departure": "Waterford",
        "destination": "Galway",
        "departure_time": "2023-11-20",
        "distance": 100,
        "class": "C",
        "energy_efficiency_rating": "low",
        "publish_timestamp": 1700504313,
        "vacancy": 2,
        "total_carbon_emission_reduction": 0
    },
    {
        "vehicle_owner_number": 1000015,
        "departure": "Cork",
        "destination": "Limerick",
        "departure_time": "2023-11-20",
        "distance": 100,
        "class": "C",
        "energy_efficiency_rating": "low",
        "publish_timestamp": 1700504313,
        "vacancy": 1,
        "total_carbon_emission_reduction": 0
    },
    {
        "vehicle_owner_number": 1000016,
        "departure": "Cork",
        "destination": "Galway",
        "departure_time": "2023-12-06",
        "distance": 50,
        "class": "C",
        "energy_efficiency_rating": "low",
        "publish_timestamp": 1700504313,
        "vacancy": 1,
        "total_carbon_emission_reduction": 0
    },
    {
        "vehicle_owner_number": 1000017,
        "departure": "Cork",
        "destination": "Waterford",
        "departure_time": "2023-11-24",
        "distance": 100,
        "class": "C",
        "energy_efficiency_rating": "low",
        "publish_timestamp": 1700504313,
        "vacancy": 5,
        "total_carbon_emission_reduction": 0
    },
    {
        "vehicle_owner_number": 1000018,
        "departure": "Galway",
        "destination": "Dublin",
        "departure_time": "2023-12-11",
        "distance": 50,
        "class": "A",
        "energy_efficiency_rating": "mid",
        "publish_timestamp": 1700504313,
        "vacancy": 6,
        "total_carbon_emission_reduction": 0
    },
    {
        "vehicle_owner_number": 1000019,
        "departure": "Galway",
        "destination": "Cork",
        "departure_time": "2023-12-11",
        "distance": 100,
        "class": "C",
        "energy_efficiency_rating": "mid",
        "publish_timestamp": 1700504313,
        "vacancy": 3,
        "total_carbon_emission_reduction": 0
    },
    {
        "vehicle_owner_number": 10000,
        "departure": "Cork",
        "destination": "Dublin",
        "departure_time": "2023-11-22",
        "distance": 50,
        "class": "B",
        "energy_efficiency_rating": "high",
        "publish_timestamp": 1700504313,
        "vacancy": 4,
        "total_carbon_emission_reduction": 0
    },
    {
        "vehicle_owner_number": 100001,
        "departure": "Dublin",
        "destination": "Cork",
        "departure_time": "2023-12-10",
        "distance": 50,
        "class": "B",
        "energy_efficiency_rating": "mid",
        "publish_timestamp": 1700504313,
        "vacancy": 5,
        "total_carbon_emission_reduction": 0
    },
    {
        "vehicle_owner_number": 100001,
        "departure": "Galway",
        "destination": "Cork",
        "departure_time": "2023-11-29",
        "distance": 100,
        "class": "A",
        "energy_efficiency_rating": "mid",
        "publish_timestamp": 1700504313,
        "vacancy": 6,
        "total_carbon_emission_reduction": 0
    },
    {
        "vehicle_owner_number": 100001,
        "departure": "Dublin",
        "destination": "Limerick",
        "departure_time": "2023-12-15",
        "distance": 100,
        "class": "B",
        "energy_efficiency_rating": "mid",
        "publish_timestamp": 1700504313,
        "vacancy": 4,
        "total_carbon_emission_reduction": 0
    },
    {
        "vehicle_owner_number": 100001,
        "departure": "Cork",
        "destination": "Dublin",
        "departure_time": "2023-12-02",
        "distance": 100,
        "class": "C",
        "energy_efficiency_rating": "mid",
        "publish_timestamp": 1700504313,
        "vacancy": 2,
        "total_carbon_emission_reduction": 0
    },
    {
        "vehicle_owner_number": 100001,
        "departure": "Waterford",
        "destination": "Limerick",
        "departure_time": "2023-12-11",
        "distance": 50,
        "class": "B",
        "energy_efficiency_rating": "mid",
        "publish_timestamp": 1700504313,
        "vacancy": 1,
        "total_carbon_emission_reduction": 0
    },
    {
        "vehicle_owner_number": 100001,
        "departure": "Dublin",
        "destination": "Waterford",
        "departure_time": "2023-11-26",
        "distance": 50,
        "class": "B",
        "energy_efficiency_rating": "high",
        "publish_timestamp": 1700504313,
        "vacancy": 6,
        "total_carbon_emission_reduction": 0
    },
    {
        "vehicle_owner_number": 100001,
        "departure": "Limerick",
        "destination": "Galway",
        "departure_time": "2023-12-03",
        "distance": 100,
        "class": "A",
        "energy_efficiency_rating": "low",
        "publish_timestamp": 1700504313,
        "vacancy": 3,
        "total_carbon_emission_reduction": 0
    },
    {
        "vehicle_owner_number": 100001,
        "departure": "Limerick",
        "destination": "Waterford",
        "departure_time": "2023-11-28",
        "distance": 100,
        "class": "B",
        "energy_efficiency_rating": "high",
        "publish_timestamp": 1700504313,
        "vacancy": 1,
        "total_carbon_emission_reduction": 0
    },
    {
        "vehicle_owner_number": 100001,
        "departure": "Galway",
        "destination": "Dublin",
        "departure_time": "2023-12-04",
        "distance": 100,
        "class": "B",
        "energy_efficiency_rating": "high",
        "publish_timestamp": 1700504313,
        "vacancy": 5,
        "total_carbon_emission_reduction": 0
    },
    {
        "vehicle_owner_number": 100001,
        "departure": "Galway",
        "destination": "Waterford",
        "departure_time": "2023-12-11",
        "distance": 50,
        "class": "C",
        "energy_efficiency_rating": "mid",
        "publish_timestamp": 1700504313,
        "vacancy": 3,
        "total_carbon_emission_reduction": 0
    }
]